# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pn07HaeeefKHC2XPxn8BTR6nUPcJ-eII
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow


def generate_pro_depth_map(left_path, right_path):
    #Load images
    img_left = cv2.imread(left_path, cv2.IMREAD_GRAYSCALE)
    img_right = cv2.imread(right_path, cv2.IMREAD_GRAYSCALE)
    #Initialize SGBM Matcher
    #minDisparity = 10 (when i comparing pixels if the num of pixels that moved is small (10>numofpixels) it will be 0)
    #numDisparities = 48 (it is searching for matched pixel in area = 48 (num must be divisable by 16))
    window_size = 5 #size of the matrix that used to match
    #P1 this for small changes in depth (Smoothing)
    #P2 this for big changes like the space between body and background
    #uniquenessRatio It compares the best matching result with the next results
    #speckleWindowSize remove small dots(Speckles)
    left_matcher = cv2.StereoSGBM_create(
        minDisparity=10,
        numDisparities=48,
        blockSize=window_size,
        P1=8 * 1 * window_size**2,
        P2=32 * 1 * window_size**2,
        disp12MaxDiff=1,
        uniquenessRatio=10,
        speckleWindowSize=100,
        speckleRange=32
    )

    #create Right Matcher (required for filtering)
    right_matcher = cv2.ximgproc.createRightMatcher(left_matcher)

    # compute Disparities
    disparityL = left_matcher.compute(img_left, img_right)
    disparityR = right_matcher.compute(img_right, img_left)

    #apply WLS Filter
    lmbda = 8000 #dgree or smoothing
    sigma = 1 #control how filter will effect the edges
    wls_filter = cv2.ximgproc.createDisparityWLSFilter(matcher_left=left_matcher)
    wls_filter.setLambda(lmbda)
    wls_filter.setSigmaColor(sigma)

    filtered_disp = wls_filter.filter(disparityL, img_left, disparity_map_right=disparityR)
    filtered_disp_float = filtered_disp.astype(np.float32)

    normalized_disp = cv2.normalize(filtered_disp_float, None, 0, 1, cv2.NORM_MINMAX)
    gamma = 1.5

    inv_log = np.exp(normalized_disp * gamma) - 1

    #scale back to 0-255
    depth_map = cv2.normalize(inv_log, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)

    cv2_imshow(depth_map)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

generate_pro_depth_map('/content/viewL.png', '/content/viewR.png')